language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libprotoc-dev
      - portaudio19-dev

script:
    - cargo build
    - cargo build --features with-tremor
    #- cargo build --features facebook
    # Building without syntex only works on nightly
    - if [[ $(rustc --version) == *"nightly"* ]]; then
        cargo build --no-default-features;
      fi
