language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libprotoc-dev
      - portaudio19-dev

script:
    - cargo build --verbose
    - cargo build --no-default-features --verbose

matrix:
  allow_failures:
    - rust:
      - stable
      - beta
