[package]
name = "librespot"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"
links = "gmp"

#[[bin]]
#name = "librespot"
#path = "src/main.rs"

[dependencies]
mod_path = "*"
byteorder = "*"
num = "*"
rand = "*"
lazy_static = "0.1.*"
rust-crypto = "*"

[dependencies.protobuf]
git = "https://github.com/plietar/rust-protobuf.git"

[dependencies.protobuf_macros]
git = "https://github.com/plietar/rust-protobuf-macros.git"

[dependencies.rust-gmp]
git = "https://github.com/plietar/rust-gmp.git"

