[package]
name = "librespot-protocol"
version = "0.1.2"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"
description="The protobuf logic for communicating with Spotify servers"
license="MIT"
edition = "2018"

[dependencies]
protobuf = "~2.16.2"

[build-dependencies]
protobuf-codegen-pure = "~2.16.2"
protobuf-codegen = "~2.16.2"
glob = "0.3.0"
