[package]
name = "librespot-protocol"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
mod_path = "*"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

